# -*- coding: utf-8 -*-
"""A/B testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw446uB70bKynkJGq2JI-gcyazUq7qSZ
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/AB Testing Data.csv")
df.head()

"""### Data Cleaning & Auditing

First, I'll filter out mismatched group-landing page assignments.
"""

initial_rows = df.shape[0]

# Filter out users in 'control' group who landed on 'new_page'
df_cleaned = df[~((df['group'] == 'control') & (df['landing_page'] == 'new_page'))]

# Filter out users in 'treatment' group who landed on 'old_page'
df_cleaned = df_cleaned[~((df_cleaned['group'] == 'treatment') & (df_cleaned['landing_page'] == 'old_page'))]

rows_after_filtering = df_cleaned.shape[0]
mismatched_rows = initial_rows - rows_after_filtering

print(f"Initial number of rows: {initial_rows}")
print(f"Number of rows after filtering mismatched assignments: {rows_after_filtering}")
print(f"Number of mismatched rows removed: {mismatched_rows}")

display(df_cleaned.head())

"""### Auditing Duplicate `user_id` Entries

Next, I'll identify and resolve any duplicate `user_id` entries to ensure each user is counted once and correctly assigned to a single group and landing page.
"""

# Check for duplicate user_ids
duplicate_users = df_cleaned[df_cleaned.duplicated(subset=['user_id'], keep=False)]

print(f"Number of duplicate user_id entries: {len(duplicate_users)}")
print(f"Number of unique users with duplicate entries: {duplicate_users['user_id'].nunique()}")

if not duplicate_users.empty:
    # Display some of the duplicate entries to understand the overlap
    print("\nExamples of duplicate user entries:")
    display(duplicate_users.sort_values(by='user_id').head())

    # Resolve session-level overlap: For simplicity and to maintain experiment integrity,
    # we will keep only the first entry for users who have multiple sessions
    # but are in the same group and saw the same landing page.
    # More critically, we'll identify users who appeared in both groups (a violation)
    # and remove them. Given the dataset structure, we'll aim for one entry per user.

    # Identify users who are in both control and treatment groups
    users_in_both_groups = df_cleaned.groupby('user_id')['group'].nunique()
    users_to_remove = users_in_both_groups[users_in_both_groups > 1].index

    if not users_to_remove.empty:
        print(f"\nUsers found in both groups (to be removed): {len(users_to_remove)}")
        df_cleaned_unique_groups = df_cleaned[~df_cleaned['user_id'].isin(users_to_remove)]
    else:
        print("\nNo users found in both control and treatment groups.")
        df_cleaned_unique_groups = df_cleaned.copy()

    # For users remaining, if they have multiple entries within the same group,
    # we'll keep the first one (assuming the first interaction is the most relevant,
    # or simply to ensure unique user_id rows for analysis).
    df_final = df_cleaned_unique_groups.drop_duplicates(subset=['user_id'], keep='first')

    rows_removed_due_to_duplicates = df_cleaned.shape[0] - df_final.shape[0]
    print(f"\nNumber of rows removed due to duplicate user_ids or users in both groups: {rows_removed_due_to_duplicates}")

    # Update df_cleaned to df_final
    df_cleaned = df_final

else:
    print("No duplicate user_id entries found.")

print(f"\nFinal number of rows after handling duplicates: {df_cleaned.shape[0]}")
display(df_cleaned.head())

"""### Format Timestamp and Check for Missing Values

I'll convert the `timestamp` column to datetime objects and then perform a final check for any missing values across all columns.
"""

# Convert 'timestamp' to datetime objects
df_cleaned['timestamp'] = pd.to_datetime(df_cleaned['timestamp'])

print("Data types after timestamp conversion:")
print(df_cleaned.info())

# Check for missing values across the entire DataFrame
missing_values = df_cleaned.isnull().sum()

print("\nMissing values per column:")
print(missing_values)

if missing_values.sum() == 0:
    print("\nNo missing values found in the DataFrame.")
else:
    print("\nMissing values detected. Further investigation may be needed.")

display(df_cleaned.head())

"""### Exploratory Data Analysis (EDA)

I will now calculate the baseline conversion rates for the control and treatment groups.
"""

conversion_rates = df_cleaned.groupby('group')['converted'].mean().reset_index()
conversion_rates['converted'] = conversion_rates['converted'] * 100
conversion_rates.rename(columns={'converted': 'conversion_rate (%)'}, inplace=True)

print("Baseline Conversion Rates:")
display(conversion_rates)

# Also, let's look at the counts for each group to ensure balanced groups
group_counts = df_cleaned['group'].value_counts().reset_index()
group_counts.rename(columns={'index': 'group', 'group': 'count'}, inplace=True)
print("\nGroup Counts:")
display(group_counts)

"""### Compare Session Length and Pages Visited

Now, I'll compare `session_duration` and `pages_visited` between converted and non-converted users to understand behavioral differences.
"""

behavioral_metrics = df_cleaned.groupby('converted')[['session_duration', 'pages_visited']].mean()

print("Average Session Duration and Pages Visited by Conversion Status:")
display(behavioral_metrics)

# Also, compare these metrics by group and conversion status
behavioral_metrics_by_group = df_cleaned.groupby(['group', 'converted'])[['session_duration', 'pages_visited']].mean()

print("\nAverage Session Duration and Pages Visited by Group and Conversion Status:")
display(behavioral_metrics_by_group)

"""### Visualize Conversions Across Device Type, Location, and Age

I will now visualize conversion rates by `device_type`, `location`, and `age` to identify any demographic or behavioral patterns.
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

# Conversion rates by Device Type
device_conversion = df_cleaned.groupby(['device_type', 'group'])['converted'].mean().unstack()
device_conversion = device_conversion * 100

print("Conversion Rates by Device Type and Group:")
display(device_conversion)

device_conversion.plot(kind='bar', figsize=(10, 6))
plt.title('Conversion Rate by Device Type and Group')
plt.ylabel('Conversion Rate (%)')
plt.xlabel('Device Type')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Conversion rates by Location
location_conversion = df_cleaned.groupby(['location', 'group'])['converted'].mean().unstack()
location_conversion = location_conversion * 100

print("Conversion Rates by Location and Group:")
display(location_conversion)

# Visualize top N locations for better readability, or all if not too many
# Let's consider top 10 locations by overall conversions
top_locations = df_cleaned.groupby('location')['converted'].mean().nlargest(10).index

location_conversion.loc[top_locations].plot(kind='bar', figsize=(12, 7))
plt.title('Conversion Rate by Location (Top 10) and Group')
plt.ylabel('Conversion Rate (%)')
plt.xlabel('Location')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Conversion rates by Age Group
# For better visualization, let's group ages into bins
age_bins = [0, 18, 25, 35, 45, 55, 65, np.inf]
age_labels = ['<18', '18-24', '25-34', '35-44', '45-54', '55-64', '65+']
df_cleaned['age_group'] = pd.cut(df_cleaned['age'], bins=age_bins, labels=age_labels, right=False)

age_conversion = df_cleaned.groupby(['age_group', 'group'])['converted'].mean().unstack()
age_conversion = age_conversion * 100

print("Conversion Rates by Age Group and Group:")
display(age_conversion)

age_conversion.plot(kind='bar', figsize=(12, 7))
plt.title('Conversion Rate by Age Group and Group')
plt.ylabel('Conversion Rate (%)')
plt.xlabel('Age Group')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Statistical Hypothesis Testing

I will now run a two-sample z-test on conversion rates to check for statistical significance.
"""

import statsmodels.api as sm
from statsmodels.stats.proportion import proportions_ztest

# Calculate conversions and total users for control and treatment groups
conversion_counts = df_cleaned.groupby('group')['converted'].agg(['sum', 'count'])

control_converted = conversion_counts.loc['control', 'sum']
control_total = conversion_counts.loc['control', 'count']
treatment_converted = conversion_counts.loc['treatment', 'sum']
treatment_total = conversion_counts.loc['treatment', 'count']

# Perform two-sample z-test
count = np.array([treatment_converted, control_converted])
nobs = np.array([treatment_total, control_total])

z_stat, p_value = proportions_ztest(count, nobs, alternative='larger') # Alternative='larger' tests if treatment > control

print(f"Control Group: {control_converted} conversions out of {control_total} users ({control_converted/control_total:.2%} conversion rate)")
print(f"Treatment Group: {treatment_converted} conversions out of {treatment_total} users ({treatment_converted/treatment_total:.2%} conversion rate)")
print(f"\nZ-statistic: {z_stat:.4f}")
print(f"P-value: {p_value:.4f}")

alpha = 0.05
if p_value < alpha:
    print(f"\nWith a p-value of {p_value:.4f} (less than alpha={alpha}), we reject the null hypothesis.")
    print("There is a statistically significant difference in conversion rates, with the treatment group converting more.")
else:
    print(f"\nWith a p-value of {p_value:.4f} (greater than or equal to alpha={alpha}), we fail to reject the null hypothesis.")
    print("There is no statistically significant difference in conversion rates between the control and treatment groups.")

# Calculate 95% Confidence Interval for the difference in proportions
# For two proportions, the CI can be calculated using a separate function or manually
from statsmodels.stats.proportion import confint_proportions_2indep

# Default method is 'wald', but 'agresti_coull' or 'jeffreys' might be more robust for small counts
conf_int_lower, conf_int_upper = confint_proportions_2indep(
    count[0], nobs[0], count[1], nobs[1],
    method='wald',
    compare='diff'
)

print(f"\n95% Confidence Interval for the difference in conversion rates (Treatment - Control): ({conf_int_lower:.4f}, {conf_int_upper:.4f})")

"""### Chi-Square Test of Independence for Sample Ratio Mismatch (SRM)

To ensure the randomization process was successful, I will perform a Chi-Square Test of Independence to check for Sample Ratio Mismatch (SRM) across different `device_type` categories. This test will help verify if the distribution of users across device types is similar in both the control and treatment groups.
"""

from scipy.stats import chi2_contingency

# Create a contingency table of 'group' vs 'device_type'
contingency_table = pd.crosstab(df_cleaned['device_type'], df_cleaned['group'])

print("Contingency Table (Device Type vs. Group):")
display(contingency_table)

# Perform the Chi-Square Test
chi2, p_value_chi2, dof, expected = chi2_contingency(contingency_table)

print(f"\nChi-Square Statistic: {chi2:.4f}")
print(f"P-value: {p_value_chi2:.4f}")
print(f"Degrees of Freedom: {dof}")

alpha_chi2 = 0.05
if p_value_chi2 < alpha_chi2:
    print(f"\nWith a p-value of {p_value_chi2:.4f} (less than alpha={alpha_chi2}), we reject the null hypothesis.")
    print("There is a statistically significant difference in the distribution of device types between the groups, indicating potential Sample Ratio Mismatch (SRM).")
else:
    print(f"\nWith a p-value of {p_value_chi2:.4f} (greater than or equal to alpha={alpha_chi2}), we fail to reject the null hypothesis.")
    print("There is no statistically significant difference in the distribution of device types between the groups, suggesting no Sample Ratio Mismatch (SRM).")

"""### Regression & Causal Inference Modeling: Logistic Regression

I will now fit a Logistic Regression model to assess the impact of the treatment group on conversion, while controlling for other factors. This will help quantify the effect of the new page and potentially identify other significant predictors of conversion.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder, PolynomialFeatures
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

# Prepare the data for Logistic Regression
# One-hot encode categorical features
df_model = df_cleaned.copy()

# Encode 'group' to numerical (0 for control, 1 for treatment)
df_model['group_encoded'] = df_model['group'].apply(lambda x: 1 if x == 'treatment' else 0)

# One-hot encode other categorical variables
df_model = pd.get_dummies(df_model, columns=['gender', 'device_type', 'location', 'age_group'], drop_first=True)

# Define features (X) and target (y)
X = df_model.drop(['user_id', 'timestamp', 'group', 'landing_page', 'converted', 'purchase_amount'], axis=1)
y = df_model['converted']

# Add 'group_encoded' to X if it's not already implicitly handled by get_dummies on 'group'
if 'group_encoded' not in X.columns:
    X['group_encoded'] = df_model['group_encoded']

# Add Interaction Terms (as per plan)
# Create polynomial features for interactions, specifically with 'group_encoded'
# Let's consider interactions between 'group_encoded' and numerical features and a few key categorical features

# Select features for interaction. We'll include numerical features and some key dummy variables.
interaction_features = ['group_encoded', 'session_duration', 'pages_visited', 'age']

# Extend interaction_features with selected dummy variables for specific interactions if desired,
# but let's start with all numerical features and the main group variable.
# Example: if you want 'group_encoded' * 'device_type_Mobile', you need 'device_type_Mobile' in X

# For simplicity and to avoid creating too many features, let's create interactions for 'group_encoded'
# with numerical features directly. Using PolynomialFeatures with degree 2 will create all 2-way interactions.
# We need to be careful not to explode the feature space, so we will manually create relevant interaction terms.

# Let's create interactions between 'group_encoded' and the numerical features:
# 'session_duration', 'pages_visited', 'age'
X['group_session_duration_interaction'] = X['group_encoded'] * X['session_duration']
X['group_pages_visited_interaction'] = X['group_encoded'] * X['pages_visited']
X['group_age_interaction'] = X['group_encoded'] * X['age']

# Now, the 'group_encoded' will interact with gender_Male etc implicitly via other interaction terms

print("Features for Logistic Regression (with interactions):")
print(X.head())
print("\nTarget variable:")
print(y.head())

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nTraining set size: {X_train.shape[0]} rows")
print(f"Testing set size: {X_test.shape[0]} rows")

# Apply SMOTE to the training data only
sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print(f"\nTraining set size after SMOTE: {X_train_res.shape[0]} rows")
print(f"Target distribution after SMOTE:\n{y_train_res.value_counts()}")

# Initialize and train the Logistic Regression model on the RESAMPLED data
log_reg_model_smote = LogisticRegression(solver='liblinear', random_state=42, max_iter=1000)
log_reg_model_smote.fit(X_train_res, y_train_res)

# Predict on the original (unresampled) test set
y_pred_smote = log_reg_model_smote.predict(X_test)
y_pred_proba_smote = log_reg_model_smote.predict_proba(X_test)[:, 1]

# Evaluate the model
print("\nLogistic Regression Model Evaluation (with SMOTE and Interactions):")
print(f"Accuracy: {accuracy_score(y_test, y_pred_smote):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_smote))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_smote))

# Interpret coefficients
print("\nModel Coefficients (Log-Odds) with SMOTE and Interactions:")
coef_df_smote = pd.DataFrame({'Feature': X.columns, 'Coefficient': log_reg_model_smote.coef_[0]})
coef_df_smote['Odds Ratio'] = np.exp(coef_df_smote['Coefficient'])
print(coef_df_smote.sort_values(by='Odds Ratio', ascending=False))

# Also, interpret the intercept
print(f"\nIntercept (Log-Odds): {log_reg_model_smote.intercept_[0]:.4f}")
print(f"Intercept (Odds): {np.exp(log_reg_model_smote.intercept_[0]):.4f}")

"""### Business Impact & Final Recommendations"""

import pandas as pd

# Calculate average purchase amount for converted users
mean_purchase_per_conversion = df_cleaned[df_cleaned['converted'] == 1]['purchase_amount'].mean()

# Calculate conversion rates and user counts for control and treatment groups
control_conversion_rate = df_cleaned[df_cleaned['group'] == 'control']['converted'].mean()
treatment_conversion_rate = df_cleaned[df_cleaned['group'] == 'treatment']['converted'].mean()

control_users = df_cleaned[df_cleaned['group'] == 'control'].shape[0]
treatment_users = df_cleaned[df_cleaned['group'] == 'treatment'].shape[0]

# Calculate expected conversions
expected_control_conversions = control_users * control_conversion_rate
expected_treatment_conversions = treatment_users * treatment_conversion_rate

# Calculate potential revenue for each group
revenue_control = expected_control_conversions * mean_purchase_per_conversion
revenue_treatment = expected_treatment_conversions * mean_purchase_per_conversion

# Calculate uplift
uplift_conversions = expected_treatment_conversions - expected_control_conversions
uplift_revenue = revenue_treatment - revenue_control

# Project revenue if all users saw treatment vs control
total_users = df_cleaned.shape[0]
projected_conversions_all_treatment = total_users * treatment_conversion_rate
projected_revenue_all_treatment = projected_conversions_all_treatment * mean_purchase_per_conversion

projected_conversions_all_control = total_users * control_conversion_rate
projected_revenue_all_control = projected_conversions_all_control * mean_purchase_per_conversion

revenue_difference_if_all_treatment = projected_revenue_all_treatment - projected_revenue_all_control

print("## A/B Testing Analysis: Landing Page Conversion Optimization\n")
print("### Key Findings & Business Impact:\n")
print(f"- **Average Purchase per Conversion:** ${mean_purchase_per_conversion:.2f}\n")
print(f"- **Control Group Conversion Rate:** {control_conversion_rate:.2%}")
print(f"- **Treatment Group Conversion Rate:** {treatment_conversion_rate:.2%}\n")
print(f"- **Experiment Revenue Uplift:** The new landing page generated an estimated **{uplift_conversions:.0f} additional conversions**, resulting in **${uplift_revenue:.2f} in increased revenue** during the test period (Treatment vs. Control)." )
print(f"- **Projected Full Rollout Impact:** If the new page were deployed to all users, it is projected to generate an **additional ${revenue_difference_if_all_treatment:.2f} in revenue** compared to the old page.\n")

print("### Actionable Recommendations:\n")
print("1.  **Deploy New Landing Page:** Given the statistically significant and substantial revenue uplift, the new landing page should be fully implemented.")
print("2.  **Leverage Geographic Insights:** Users from specific locations (US, India, UK, Canada, Pakistan, Germany) show much higher conversion odds. Consider targeted marketing campaigns or localized content for these regions.")
print("3.  **Target by Age Group:** Different age groups exhibit varying conversion odds. Tailor content and offers to specific age segments to maximize engagement and conversion.")
print("4.  **Optimize for Devices:** Mobile and tablet users show slightly higher odds of conversion. Ensure the new page is highly optimized for these devices.")
print("5.  **Continuous Monitoring:** Implement ongoing monitoring of conversion rates and key metrics post-deployment to confirm sustained performance and identify long-term trends.")
print("6.  **Further A/B Tests:** Conduct additional A/B tests to refine specific elements of the new page or explore new variations. Test specific offers or messaging tailored to high-performing segments.")

"""### Revenue Impact Across Locations Visualization

To better understand the business impact by region, I will visualize the total revenue generated from converted users for each location.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate total revenue per location from converted users
revenue_by_location = df_cleaned[df_cleaned['converted'] == 1].groupby('location')['purchase_amount'].sum().reset_index()

# Sort by revenue for better visualization
revenue_by_location = revenue_by_location.sort_values(by='purchase_amount', ascending=False)

plt.figure(figsize=(14, 7))
sns.barplot(x='location', y='purchase_amount', data=revenue_by_location, palette='viridis', hue='location', legend=False)
plt.title('Total Revenue from Converted Users by Location')
plt.xlabel('Location')
plt.ylabel('Total Revenue ($)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()